In [ ]:
import pandas as pd

viajes = pd.read_csv('df_distancias_finales.csv')
viajes['tsO'] = pd.to_datetime(viajes['tsO'])
viajes['tsD'] = pd.to_datetime(viajes['tsD'])
viajes['tsO_min'] = pd.to_datetime(viajes['tsO']).dt.floor('min')
viajes['tsD_min'] = pd.to_datetime(viajes['tsD']).dt.floor('min')
stations = pd.read_csv('centroides2.csv')
distribution = pd.read_json('optimos_semanales.json')
errores = pd.read_csv('errores.csv')
errores.head()

  Patin               Minuto
0  R1H3  2021-02-01 07:49:00
1  W2T5  2021-02-01 07:52:00
2  E8F9  2021-02-01 08:10:00
3  T7J4  2021-02-01 08:31:00
4  R0J4  2021-02-01 08:33:00

In [ ]:
viajes = viajes[['idS', 'tsO_min', 'tsD_min', 'clusterOrigen', 'clusterFinal', 'energy_wh']]
print(viajes.shape)
for index, row in viajes.iterrows():
  for index2, row2 in errores.iterrows():
      if row['idS'] == row2['Patin'] and row['tsO_min'] == pd.to_datetime(row2['Minuto']) or row['idS'] == row2['Patin'] and row['tsD_min'] == pd.to_datetime(row2['Minuto']):
          print('OK')
          viajes.drop(index, inplace=True)
          break
print(viajes.shape)

(20397, 6)
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
(19912, 6)

In [ ]:
viajes.to_csv('viajes_finales.csv', index=False)

In [1]:
#### Ejecutar a partir de aqui

In [162]:
import pandas as pd

viajes = pd.read_csv('viajes_finales.csv')
viajes['tsO_min'] = pd.to_datetime(viajes['tsO_min'])
viajes['tsD_min'] = pd.to_datetime(viajes['tsD_min'])
viajes.drop(index=[4402, 5648, 11903, 14196, 8636, 9296, 8504, 209, 13251, 1464, 16072, 19783], inplace=True)
stations = pd.read_csv('centroides2.csv')
distribution = pd.read_json('optimos_semanales.json')
errores = pd.read_csv('errores.csv')
capacidad = pd.read_csv('capacidad_recarga.csv')
capacidad.head(1)

,Estacion_ID,Estacion_ID.1,Día 1,Día 2,Día 3,Día 4,Día 5,Día 6,Día 7,Día 8,...,Día 19,Día 20,Día 21,Día 22,Día 23,Día 24,Día 25,Día 26,Día 27,Día 28
0,0,0,"{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....",...,"{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0....","{0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0...."

In [163]:
import numpy as np
import pandas as pd
import ast

start_time = f'2021-02-01 00:00:00'
end_time = f'2021-02-07 23:59:00'
minutos = pd.date_range(start=start_time, end=end_time, freq='min')

bicis_semana_1 = list(np.arange(790))

station_columns = [f'station{i}' for i in range(190)]
simulations_df = pd.DataFrame(index=minutos, columns=station_columns)

simulations_df.loc[minutos[0]] = [[r['2021-02-01'][0], r['2021-02-01'][1], {bicis_semana_1.pop(0): 576 for _ in range(int(r['2021-02-01'][1]))}, np.floor(ast.literal_eval(capacidad.iloc[int(index.split('n')[1])]['Día 1'])[0]), ast.literal_eval(capacidad.iloc[int(index.split('n')[1])]['Día 1'])[0] - np.floor(ast.literal_eval(capacidad.iloc[int(index.split('n')[1])]['Día 1'])[0])] for index,r in distribution.iterrows()]

In [166]:
def carga_patines(capacidad: float, patines: dict, CTE_CARGA: float = 72/60) -> dict:
  if len(patines) <= capacidad:
    for patin, carga in patines.items():
      if carga <= 576 - CTE_CARGA:
        patines[patin] = carga + CTE_CARGA
      else:
        patines[patin] = 576
  else:
    patines_ordenados = sorted(patines.items(), key=lambda x: x[1], reverse=False)
    a_cargar = patines_ordenados[:int(capacidad)]

    for patin_id, carga_actual in a_cargar:
      if carga_actual <= 576 - CTE_CARGA:
        patines[patin_id] = carga_actual + CTE_CARGA
      else:
        patines[patin_id] = 576
  return patines

In [167]:
import pandas as pd
import numpy as np
import ast

saltar = []

# Iteramos sobre los minutos
for i, minuto in enumerate(minutos[1:]):
    # 1. Copiar el estado completo del minuto anterior al actual
    simulations_df.loc[minuto] = simulations_df.loc[minutos[i]]

    # -------------------------------------------------------------------------
    # CORRECCIÓN CLAVE: ACTUALIZAR CAPACIDAD Y RESTANTES AL INICIO DE HORA
    # -------------------------------------------------------------------------
    # Solo recalculamos la capacidad de carga si entramos en una nueva hora.
    # Si no es minuto 0, la capacidad y el restante se mantienen iguales al minuto anterior (ya copiados arriba).
    if minuto.minute == 0:
        for col in simulations_df.columns:
            if 'station' in col:
                try:
                    # Recuperamos el estado que acabamos de copiar del minuto anterior
                    current_capacity, current_occupation, patines, cap_carga_actual, restante_acumulado = simulations_df.loc[minuto, col]

                    # Obtenemos el valor crudo para la NUEVA hora actual
                    station_idx = int(col.split('n')[1]) # extraer ID de stationX
                    datos_hoy = ast.literal_eval(capacidad.iloc[station_idx][f'Día {minuto.day}'])
                    valor_crudo_nueva_hora = datos_hoy[minuto.hour]

                    # AQUÍ ESTÁ LA SOLUCIÓN:
                    # Sumamos el valor de la nueva hora + el restante que venía acumulado en el dataframe
                    total_disponible = valor_crudo_nueva_hora + restante_acumulado

                    nueva_capacidad_carga = np.floor(total_disponible)
                    nuevo_restante = total_disponible - nueva_capacidad_carga

                    # Actualizamos el estado del minuto actual con los nuevos valores de carga
                    simulations_df.loc[minuto, col] = (current_capacity, current_occupation, patines, nueva_capacidad_carga, nuevo_restante)

                except Exception as e:
                    # Manejo de errores si faltan datos en la tabla 'capacidad'
                    print(f"Error actualizando capacidad en {col} a las {minuto}: {e}")
                    pass

    # -------------------------------------------------------------------------
    # PROCESAMIENTO DE VIAJES (SALIDAS)
    # -------------------------------------------------------------------------
    trips_starting_now = viajes[viajes['tsO_min'] == minuto]

    for index, row in trips_starting_now.iterrows():
        origen_cluster = int(row['clusterOrigen'])
        station_col = f'station{origen_cluster}'

        if station_col in simulations_df.columns:
            # Leemos el estado actual (que ya tiene la capacidad actualizada si era necesario)
            current_capacity, current_occupation, patines, capacidad_carga, restante_carga = simulations_df.loc[minuto, station_col]

            if current_occupation == 0:
                # No hay bicis, saltamos el viaje
                saltar.append(index)
            else:
                # Lógica para elegir la bici con más carga
                max_id = 0
                max_carga = -1
                for patin, carga in patines.items():
                    if carga > max_carga:
                        max_id = patin
                        max_carga = carga

                # Retiramos el patín
                if max_id != 0:
                    del patines[max_id]

                # Actualizamos SOLO ocupación y lista de patines.
                # NO tocamos capacidad_carga ni restante_carga (se mantienen igual)
                simulations_df.loc[minuto, station_col] = (current_capacity, max(0.0, int(current_occupation) - 1.0), patines, capacidad_carga, restante_carga)

                # Registramos datos en el viaje
                viajes.loc[index, ['id', 'carga_inicial']] = [max_id, max_carga]

    # -------------------------------------------------------------------------
    # PROCESAMIENTO DE VIAJES (LLEGADAS)
    # -------------------------------------------------------------------------
    trips_ending_now = viajes[viajes['tsD_min'] == minuto]

    for index, row in trips_ending_now.iterrows():
        if index in saltar:
            continue

        destino_cluster = int(row['clusterFinal'])
        station_col = f'station{destino_cluster}'

        if station_col in simulations_df.columns:
            # Leemos estado actual (puede haber cambiado por una salida en este mismo minuto)
            current_capacity, current_occupation, patines, capacidad_carga, restante_carga = simulations_df.loc[minuto, station_col]

            if int(current_occupation) >= int(current_capacity):
                # Estación llena (lógica de rechazo, el estado no cambia)
                pass
            else:
                # Añadimos el patín con la carga restante
                patines[row['id']] = row['carga_inicial'] - row['energy_wh']

                # Actualizamos SOLO ocupación y lista de patines
                simulations_df.loc[minuto, station_col] = (current_capacity, max(0.0, int(current_occupation) + 1.0), patines, capacidad_carga, restante_carga)


    for station_col in simulations_df.columns:
        current_capacity, current_occupation, patines, capacidad_carga, restante_carga = simulations_df.loc[minuto, station_col]
        patines_antes = patines.copy()

        # Ejecutamos la carga
        patines_cargados = carga_patines(capacidad_carga, patines)

        # Guardamos el resultado en el dataframe
        simulations_df.loc[minuto, station_col] = (current_capacity, current_occupation, patines_cargados, capacidad_carga, restante_carga)

        # --- AQUÍ ESTÁ EL PRINT DE VERIFICACIÓN ---
        # Filtros: Estación 189, con hueco de carga, con patines, y al cambio de hora
        if station_col == 'station189' and capacidad_carga > 0 and len(patines) > 0 and minuto.minute == 0:
            print(f"\n⚡ VERIFICACIÓN CARGA [{minuto}] - {station_col}")
            print(f"   |> Capacidad de carga (huecos): {capacidad_carga}")
            print(f"   |> IDs y Carga ANTES:   {sorted(patines_antes.items(), key=lambda x: x[1], reverse=True)}")
            print(f"   |> IDs y Carga DESPUÉS: {sorted(patines_cargados.items(), key=lambda x: x[1], reverse=True)}")

            # Calculamos cuánto subió cada uno para verificar que sea igual a CTE_CARGA
            cambios = []
            for pid, carga_final in patines_cargados.items():
                carga_inicial = patines_antes.get(pid, 0)
                if carga_final > carga_inicial:
                    cambios.append(f"ID {pid}: +{carga_final - carga_inicial:.2f}")

            print(f"   |> Incrementos aplicados: {cambios}")
            print("-" * 60)
    # -------------------------------------------------------------------------
    # LOGS / DEBUG
    # -------------------------------------------------------------------------
    # Ejemplo de log para verificar una estación específica
    if minuto.minute == 0: # Chequear solo cambio de hora
        print(f"DEBUG {minuto}: Station 189 -> CapCarga: {simulations_df.loc[minuto, 'station189'][3]}, Restante: {simulations_df.loc[minuto, 'station189'][4]}")

    patinetes_totales = {}
    for estado_tupla in simulations_df.loc[minuto]:
         # Aseguramos desempaquetado seguro por si acaso hay nans
         if isinstance(estado_tupla, tuple):
            capacidad_estacion, ocupacion, dict_patines, capacidad_carga, restante_carga = estado_tupla
            patinetes_totales.update(dict_patines)

    # print(f'En el minuto {minuto} hay {len(patinetes_totales.keys())} patinetes totales en el sistema.')

DEBUG 2021-02-01 01:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.0
DEBUG 2021-02-01 02:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.0
DEBUG 2021-02-01 03:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.0
DEBUG 2021-02-01 04:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.0
DEBUG 2021-02-01 05:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.0
DEBUG 2021-02-01 06:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.0
DEBUG 2021-02-01 07:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.0
DEBUG 2021-02-01 08:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.25676388888888885

⚡ VERIFICACIÓN CARGA [2021-02-01 09:00:00] - station189
   |> Capacidad de carga (huecos): 3.0
   |> IDs y Carga ANTES:   [(169.0, 564.9331181774248), (170.0, 564.9331181774248), (433.0, 514.9799330494251), (435.0, 514.9799330494251), (722.0, 511.352759882436), (723.0, 511.352759882436)]
   |> IDs y Carga DESPUÉS: [(169.0, 564.9331181774248), (170.0, 564.9331181774248), (433.0, 516.1799330494251), (435.0, 514.9799330494251), (722.0, 512.552759882436), (723.0, 512.552759882436)]
   |> Incrementos aplicados: ['ID 433.0: +1.20', 'ID 722.0: +1.20', 'ID 723.0: +1.20']
------------------------------------------------------------
DEBUG 2021-02-01 09:00:00: Station 189 -> CapCarga: 3.0, Restante: 0.9475555555555562

⚡ VERIFICACIÓN CARGA [2021-02-01 10:00:00] - station189
   |> Capacidad de carga (huecos): 6.0
   |> IDs y Carga ANTES:   [(433.0, 566.579933049427), (435.0, 566.579933049427), (722.0, 566.5527598824381), (723.0, 566.5527598824381), (169.0, 566.1331181774249), (170.0, 566.1331181774249)]
   |> IDs y Carga DESPUÉS: [(433.0, 567.7799330494271), (435.0, 567.7799330494271), (722.0, 567.7527598824381), (723.0, 567.7527598824381), (169.0, 567.3331181774249), (170.0, 567.3331181774249)]
   |> Incrementos aplicados: ['ID 433.0: +1.20', 'ID 722.0: +1.20', 'ID 169.0: +1.20', 'ID 435.0: +1.20', 'ID 723.0: +1.20', 'ID 170.0: +1.20']
------------------------------------------------------------
DEBUG 2021-02-01 10:00:00: Station 189 -> CapCarga: 6.0, Restante: 0.6996805555555561

⚡ VERIFICACIÓN CARGA [2021-02-01 11:00:00] - station189
   |> Capacidad de carga (huecos): 3.0
   |> IDs y Carga ANTES:   [(433.0, 576), (722.0, 576), (169.0, 576), (435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576)]
   |> IDs y Carga DESPUÉS: [(433.0, 576), (722.0, 576), (169.0, 576), (435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-01 11:00:00: Station 189 -> CapCarga: 3.0, Restante: 0.4218888888888892

⚡ VERIFICACIÓN CARGA [2021-02-01 12:00:00] - station189
   |> Capacidad de carga (huecos): 5.0
   |> IDs y Carga ANTES:   [(433.0, 576), (722.0, 576), (169.0, 576), (435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576)]
   |> IDs y Carga DESPUÉS: [(433.0, 576), (722.0, 576), (169.0, 576), (435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-01 12:00:00: Station 189 -> CapCarga: 5.0, Restante: 0.48493055555555564

⚡ VERIFICACIÓN CARGA [2021-02-01 13:00:00] - station189
   |> Capacidad de carga (huecos): 3.0
   |> IDs y Carga ANTES:   [(433.0, 576), (722.0, 576), (169.0, 576), (435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576)]
   |> IDs y Carga DESPUÉS: [(433.0, 576), (722.0, 576), (169.0, 576), (435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-01 13:00:00: Station 189 -> CapCarga: 3.0, Restante: 0.28876388888888904

⚡ VERIFICACIÓN CARGA [2021-02-01 14:00:00] - station189
   |> Capacidad de carga (huecos): 5.0
   |> IDs y Carga ANTES:   [(433.0, 576), (722.0, 576), (169.0, 576), (435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576)]
   |> IDs y Carga DESPUÉS: [(433.0, 576), (722.0, 576), (169.0, 576), (435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-01 14:00:00: Station 189 -> CapCarga: 5.0, Restante: 0.7549305555555561

⚡ VERIFICACIÓN CARGA [2021-02-01 15:00:00] - station189
   |> Capacidad de carga (huecos): 4.0
   |> IDs y Carga ANTES:   [(433.0, 576), (722.0, 576), (169.0, 576), (435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576)]
   |> IDs y Carga DESPUÉS: [(433.0, 576), (722.0, 576), (169.0, 576), (435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-01 15:00:00: Station 189 -> CapCarga: 4.0, Restante: 0.31194444444444525

⚡ VERIFICACIÓN CARGA [2021-02-01 16:00:00] - station189
   |> Capacidad de carga (huecos): 1.0
   |> IDs y Carga ANTES:   [(433.0, 576), (722.0, 576), (169.0, 576), (435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576)]
   |> IDs y Carga DESPUÉS: [(433.0, 576), (722.0, 576), (169.0, 576), (435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-01 16:00:00: Station 189 -> CapCarga: 1.0, Restante: 0.6012361111111117
DEBUG 2021-02-01 17:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-01 18:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-01 19:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-01 20:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-01 21:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-01 22:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-01 23:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-02 00:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-02 01:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-02 02:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-02 03:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-02 04:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-02 05:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-02 06:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117
DEBUG 2021-02-02 07:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6012361111111117

⚡ VERIFICACIÓN CARGA [2021-02-02 08:00:00] - station189
   |> Capacidad de carga (huecos): 1.0
   |> IDs y Carga ANTES:   [(435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576), (413.0, 544.4789592997955), (702.0, 479.70793804942286)]
   |> IDs y Carga DESPUÉS: [(435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576), (413.0, 544.4789592997955), (702.0, 480.90793804942285)]
   |> Incrementos aplicados: ['ID 702.0: +1.20']
------------------------------------------------------------
DEBUG 2021-02-02 08:00:00: Station 189 -> CapCarga: 1.0, Restante: 0.8786527777777784

⚡ VERIFICACIÓN CARGA [2021-02-02 09:00:00] - station189
   |> Capacidad de carga (huecos): 4.0
   |> IDs y Carga ANTES:   [(435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576), (413.0, 544.4789592997955), (702.0, 539.7079380494237), (461.0, 539.4877799726706)]
   |> IDs y Carga DESPUÉS: [(435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576), (413.0, 545.6789592997956), (702.0, 540.9079380494237), (461.0, 540.6877799726707)]
   |> Incrementos aplicados: ['ID 413.0: +1.20', 'ID 702.0: +1.20', 'ID 461.0: +1.20']
------------------------------------------------------------
DEBUG 2021-02-02 09:00:00: Station 189 -> CapCarga: 4.0, Restante: 0.6598750000000004

⚡ VERIFICACIÓN CARGA [2021-02-02 10:00:00] - station189
   |> Capacidad de carga (huecos): 6.0
   |> IDs y Carga ANTES:   [(435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576)]
   |> IDs y Carga DESPUÉS: [(435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-02 10:00:00: Station 189 -> CapCarga: 6.0, Restante: 0.5798194444444444

⚡ VERIFICACIÓN CARGA [2021-02-02 11:00:00] - station189
   |> Capacidad de carga (huecos): 7.0
   |> IDs y Carga ANTES:   [(435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576)]
   |> IDs y Carga DESPUÉS: [(435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-02 11:00:00: Station 189 -> CapCarga: 7.0, Restante: 0.8312083333333335

⚡ VERIFICACIÓN CARGA [2021-02-02 12:00:00] - station189
   |> Capacidad de carga (huecos): 8.0
   |> IDs y Carga ANTES:   [(435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576)]
   |> IDs y Carga DESPUÉS: [(435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-02 12:00:00: Station 189 -> CapCarga: 8.0, Restante: 0.5003749999999982

⚡ VERIFICACIÓN CARGA [2021-02-02 13:00:00] - station189
   |> Capacidad de carga (huecos): 7.0
   |> IDs y Carga ANTES:   [(435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576), (483.0, 576), (436.0, 576)]
   |> IDs y Carga DESPUÉS: [(435.0, 576), (723.0, 576), (170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576), (483.0, 576), (436.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-02 13:00:00: Station 189 -> CapCarga: 7.0, Restante: 0.7231666666666658

⚡ VERIFICACIÓN CARGA [2021-02-02 14:00:00] - station189
   |> Capacidad de carga (huecos): 6.0
   |> IDs y Carga ANTES:   [(723.0, 576), (170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576), (483.0, 576), (436.0, 576)]
   |> IDs y Carga DESPUÉS: [(723.0, 576), (170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576), (483.0, 576), (436.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-02 14:00:00: Station 189 -> CapCarga: 6.0, Restante: 0.588763888888888

⚡ VERIFICACIÓN CARGA [2021-02-02 15:00:00] - station189
   |> Capacidad de carga (huecos): 4.0
   |> IDs y Carga ANTES:   [(723.0, 576), (170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576), (483.0, 576), (436.0, 576)]
   |> IDs y Carga DESPUÉS: [(723.0, 576), (170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576), (483.0, 576), (436.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-02 15:00:00: Station 189 -> CapCarga: 4.0, Restante: 0.3398611111111105

⚡ VERIFICACIÓN CARGA [2021-02-02 16:00:00] - station189
   |> Capacidad de carga (huecos): 1.0
   |> IDs y Carga ANTES:   [(170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576), (483.0, 576), (436.0, 576)]
   |> IDs y Carga DESPUÉS: [(170.0, 576), (683.0, 576), (413.0, 576), (702.0, 576), (461.0, 576), (606.0, 576), (483.0, 576), (436.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-02 16:00:00: Station 189 -> CapCarga: 1.0, Restante: 0.7624305555555548
DEBUG 2021-02-02 17:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-02 18:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-02 19:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-02 20:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-02 21:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-02 22:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-02 23:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-03 00:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-03 01:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-03 02:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-03 03:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-03 04:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-03 05:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-03 06:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-03 07:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-03 08:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.7624305555555548
DEBUG 2021-02-03 09:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.9848333333333327

⚡ VERIFICACIÓN CARGA [2021-02-03 10:00:00] - station189
   |> Capacidad de carga (huecos): 2.0
   |> IDs y Carga ANTES:   [(461.0, 576), (606.0, 576), (483.0, 576), (436.0, 576), (610.0, 511.352759882436), (736.0, 507.4501561449553), (91.0, 483.5970594974724)]
   |> IDs y Carga DESPUÉS: [(461.0, 576), (606.0, 576), (483.0, 576), (436.0, 576), (610.0, 511.352759882436), (736.0, 508.6501561449553), (91.0, 484.7970594974724)]
   |> Incrementos aplicados: ['ID 91.0: +1.20', 'ID 736.0: +1.20']
------------------------------------------------------------
DEBUG 2021-02-03 10:00:00: Station 189 -> CapCarga: 2.0, Restante: 0.2521249999999995

⚡ VERIFICACIÓN CARGA [2021-02-03 11:00:00] - station189
   |> Capacidad de carga (huecos): 1.0
   |> IDs y Carga ANTES:   [(461.0, 576), (606.0, 576), (483.0, 576), (436.0, 576), (736.0, 549.4501561449567), (610.0, 548.5527598824374), (91.0, 548.3970594974735)]
   |> IDs y Carga DESPUÉS: [(461.0, 576), (606.0, 576), (483.0, 576), (436.0, 576), (91.0, 549.5970594974735), (736.0, 549.4501561449567), (610.0, 548.5527598824374)]
   |> Incrementos aplicados: ['ID 91.0: +1.20']
------------------------------------------------------------
DEBUG 2021-02-03 11:00:00: Station 189 -> CapCarga: 1.0, Restante: 0.7208333333333328

⚡ VERIFICACIÓN CARGA [2021-02-03 12:00:00] - station189
   |> Capacidad de carga (huecos): 2.0
   |> IDs y Carga ANTES:   [(606.0, 576), (483.0, 576), (436.0, 576), (736.0, 573.4501561449576), (610.0, 572.5527598824383), (91.0, 572.3970594974744)]
   |> IDs y Carga DESPUÉS: [(606.0, 576), (483.0, 576), (436.0, 576), (610.0, 573.7527598824383), (91.0, 573.5970594974744), (736.0, 573.4501561449576)]
   |> Incrementos aplicados: ['ID 91.0: +1.20', 'ID 610.0: +1.20']
------------------------------------------------------------
DEBUG 2021-02-03 12:00:00: Station 189 -> CapCarga: 2.0, Restante: 0.33284722222222163

⚡ VERIFICACIÓN CARGA [2021-02-03 13:00:00] - station189
   |> Capacidad de carga (huecos): 2.0
   |> IDs y Carga ANTES:   [(483.0, 576), (436.0, 576), (91.0, 576), (610.0, 576), (736.0, 576), (0.0, 576)]
   |> IDs y Carga DESPUÉS: [(483.0, 576), (436.0, 576), (91.0, 576), (610.0, 576), (736.0, 576), (0.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-03 13:00:00: Station 189 -> CapCarga: 2.0, Restante: 0.19151388888888832

⚡ VERIFICACIÓN CARGA [2021-02-03 14:00:00] - station189
   |> Capacidad de carga (huecos): 1.0
   |> IDs y Carga ANTES:   [(436.0, 576), (91.0, 576), (610.0, 576), (736.0, 576), (0.0, 576)]
   |> IDs y Carga DESPUÉS: [(436.0, 576), (91.0, 576), (610.0, 576), (736.0, 576), (0.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-03 14:00:00: Station 189 -> CapCarga: 1.0, Restante: 0.41349999999999953

⚡ VERIFICACIÓN CARGA [2021-02-03 15:00:00] - station189
   |> Capacidad de carga (huecos): 1.0
   |> IDs y Carga ANTES:   [(436.0, 576), (91.0, 576), (610.0, 576), (736.0, 576), (0.0, 576), (94.0, 537.0815606359893)]
   |> IDs y Carga DESPUÉS: [(436.0, 576), (91.0, 576), (610.0, 576), (736.0, 576), (0.0, 576), (94.0, 538.2815606359893)]
   |> Incrementos aplicados: ['ID 94.0: +1.20']
------------------------------------------------------------
DEBUG 2021-02-03 15:00:00: Station 189 -> CapCarga: 1.0, Restante: 0.5391249999999996
DEBUG 2021-02-03 16:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-03 17:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-03 18:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-03 19:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-03 20:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-03 21:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-03 22:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-03 23:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-04 00:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-04 01:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-04 02:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-04 03:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-04 04:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-04 05:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-04 06:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-04 07:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5600694444444441
DEBUG 2021-02-04 08:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.5942638888888885
DEBUG 2021-02-04 09:00:00: Station 189 -> CapCarga: 0.0, Restante: 0.6553055555555551

⚡ VERIFICACIÓN CARGA [2021-02-04 10:00:00] - station189
   |> Capacidad de carga (huecos): 4.0
   |> IDs y Carga ANTES:   [(610.0, 576), (736.0, 576), (94.0, 576), (351.0, 540.032656218875), (84.0, 488.07102172642055), (0.0, -28.44928217405874)]
   |> IDs y Carga DESPUÉS: [(610.0, 576), (736.0, 576), (94.0, 576), (351.0, 541.232656218875), (84.0, 489.27102172642054), (0.0, -27.24928217405874)]
   |> Incrementos aplicados: ['ID 0.0: +1.20', 'ID 84.0: +1.20', 'ID 351.0: +1.20']
------------------------------------------------------------
DEBUG 2021-02-04 10:00:00: Station 189 -> CapCarga: 4.0, Restante: 0.221597222222222

⚡ VERIFICACIÓN CARGA [2021-02-04 11:00:00] - station189
   |> Capacidad de carga (huecos): 1.0
   |> IDs y Carga ANTES:   [(610.0, 576), (736.0, 576), (94.0, 576), (351.0, 576), (0.0, 565.4982169819635), (84.0, 560.0710217264221)]
   |> IDs y Carga DESPUÉS: [(610.0, 576), (736.0, 576), (94.0, 576), (351.0, 576), (0.0, 565.4982169819635), (84.0, 561.2710217264222)]
   |> Incrementos aplicados: ['ID 84.0: +1.20']
------------------------------------------------------------
DEBUG 2021-02-04 11:00:00: Station 189 -> CapCarga: 1.0, Restante: 0.031041666666666412

⚡ VERIFICACIÓN CARGA [2021-02-04 12:00:00] - station189
   |> Capacidad de carga (huecos): 4.0
   |> IDs y Carga ANTES:   [(610.0, 576), (736.0, 576), (0.0, 576), (94.0, 576), (84.0, 576), (351.0, 576)]
   |> IDs y Carga DESPUÉS: [(610.0, 576), (736.0, 576), (0.0, 576), (94.0, 576), (84.0, 576), (351.0, 576)]
   |> Incrementos aplicados: []
------------------------------------------------------------
DEBUG 2021-02-04 12:00:00: Station 189 -> CapCarga: 4.0, Restante: 0.35515277777777854

⚡ VERIFICACIÓN CARGA [2021-02-04 13:00:00] - station189
   |> Capacidad de carga (huecos): 5.0

In [169]:
simulations_df.tail(1)

,station0,station1,station2,station3,station4,station5,station6,station7,station8,station9,...,station180,station181,station182,station183,station184,station185,station186,station187,station188,station189
2021-02-07 23:59:00,"(16, 16.0, {0.0: 576, 171.0: 576, 697.0: 576, ...","(16, 3.0, {0: 576, 250.0: 576, 11.0: 576, 168....","(12, 0.0, {0.0: 576, 657.0: 576, 181.0: 576}, ...","(11, 0.0, {0.0: 576, 82.0: 576, 787.0: 576}, 0...","(11, 6.0, {0.0: 576, 488.0: 576, 404.0: 576, 4...","(15, 0.0, {0.0: 576, 207.0: 576, 30.0: 576, 46...","(16, 12.0, {400.0: 576, 196.0: 576, 770.0: 576...","(7, 5.0, {0.0: 561.5481914955392, 36.0: 576, 4...","(12, 2.0, {355.0: 576, 358.0: 576}, 0.0, 0.460...","(9, 4.0, {0.0: 576, 20.0: 576, 493.0: 576, 630...",...,"(8, 0.0, {0.0: 576}, 0.0, 0.293652777777777)","(8, 1.0, {0.0: 576, 384.0: 576, 328.0: 576}, 0...","(8, 5.0, {0.0: 576, 223.0: 576, 290.0: 576}, 0...","(9, 1.0, {663.0: 576}, 0.0, 0.16136111111111062)","(16, 0.0, {0.0: 576, 382.0: 576, 634.0: 576}, ...","(16, 11.0, {0.0: 567.3570553225652, 379.0: 576...","(11, 3.0, {0.0: 576, 264.0: 576, 114.0: 576, 2...","(6, 2.0, {0.0: 576, 494.0: 576}, 0.0, 0.518236...","(7, 1.0, {0.0: 576, 527.0: 576, 25.0: 576, 377...","(15, 12.0, {0.0: 576, 351.0: 576, 50.0: 576, 3..."

In [178]:
patines_finales = {}
df_ultima_fila = simulations_df.tail(1)

# Usamos iterrows() para obtener el índice de la última fila
for index, row in df_ultima_fila.iterrows():

    # 1. Obtenemos solo los NOMBRES de las columnas que contienen 'station'
    columnas_station = [c for c in df_ultima_fila.columns if 'station' in c]

    # 2. Iteramos sobre esos NOMBRES de columna
    for col_name in columnas_station:

        # 3. Accedemos al valor de la celda.
        #    ESTE VALOR DEBE SER UNA LISTA O TUPLA DE 5 ELEMENTOS
        datos_de_celda = df_ultima_fila.loc[index, col_name]

        # 4. Desempaquetamos los 5 elementos
        try:
            current_capacity, current_occupation, patines, capacidad_carga, restante_carga = datos_de_celda

            # 5. Si todo funciona, actualizamos el diccionario 'patines_finales'
            patines_finales.update(patines)

        except ValueError as e:
            # Capturamos el error si la celda no contiene 5 valores
            print(f"Error al desempaquetar la celda '{col_name}': {e}")
            print(f"El valor de la celda es: {datos_de_celda}")
            # Puedes usar 'continue' si quieres saltar esta celda y seguir con la siguiente
            # continue

print(sorted(patines_finales.values()))

[472.7901382370332, 476.76142865325073, 498.90142095874376, 499.18964769052457, 507.0802955905509, 510.1049257083182, 513.8743996664261, 514.2887530316553, 514.364726026189, 518.4071764557358, 520.4070428809098, 523.5194377831979, 523.7886020536203, 524.5451948124744, 525.9503027766848, 525.9553852868816, 527.9791926422089, 529.2284939718509, 529.4432133368028, 530.8800805288221, 531.9430860413792, 532.3980065441968, 532.5453082111336, 533.9481693992802, 534.1376188210068, 535.2324843562297, 536.2672464322271, 536.6310909444073, 540.0265075096843, 540.2221246570532, 540.9746377280003, 541.3927075431798, 542.9723350216318, 543.4319070540108, 544.3680628258747, 546.2762730981098, 546.6520403163894, 546.9885131155297, 547.3430131571714, 547.4867068147965, 547.75467992605, 548.1871633563117, 548.1871633563117, 549.8860529346005, 550.1783227258986, 550.8636553229742, 552.5320745935585, 553.7717142685142, 553.8885568780628, 554.7470362940195, 554.9739097681858, 555.2844265302708, 555.8954544782922, 556.145089093808, 557.141293392701, 557.4485716870905, 558.3051582699815, 558.4454229884672, 559.9913903752861, 560.2841153415706, 561.4268172453174, 562.1934547285388, 562.4254063028185, 562.8811106942768, 566.1057066263153, 566.9587212709117, 568.0503718235894, 568.3733660759896, 568.4193870998928, 568.4932960146765, 569.6058034082482, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576, 576]